apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverread-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serverread
  minReadySeconds: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: serverread
    spec:
      containers:
      - name: serverread
        image: michaelok1997/serverread:latest
        ports:
        - containerPort: 50052